name: Build and Release JAR

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Важно для создания релизов

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        # Звездочка здесь работает, загрузятся все JAR из target
        files: target/*.jar 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
